Add code to test GenAI-Bench-1600 dataset
linzhiqiu/t2v_metrics pull request #12
Opened 2024-07-21 16:57 UTC by Baiqi-Li

1. Added `GenAI_Bench_Image_1600` class in `dataset.py` to load and test GenAI-Bench-1600 from Hugging Face.
2. Created `genai_image_eval_1600.py` for testing GenAI-Bench-1600 (batch processing not supported yet).
3. Updated `image_loader` function in `/t2v_metrics/t2v_metrics/models/model.py` to support `Image.Image` objects.

2024-08-07 19:41 UTC, linzhiqiu requested changes

2024-08-07 19:41 UTC, linzhiqiu commented on genai_image_eval_1600.py
> +from dataset import GenAIBench_Image, GenAI_Bench_Image_1600
We should maximize code reuse and make sure the naming are consistent

2024-09-16 20:07 UTC, Baiqi-Li commented on dataset.py
> +class GenAI_Bench_Image_1600(Dataset):
Okay! I have finished.

2025-01-01 11:14 UTC, linzhiqiu requested changes

2025-01-01 11:14 UTC, linzhiqiu commented on dataset.py
> +        else:
This is not robust. What if someone inputs 800? If we only support 527 and 1600, then we should use assert to check no other options are passed in

2025-01-01 11:14 UTC, linzhiqiu commented on dataset.py
> +                    else:
same here

2025-01-01 11:14 UTC, linzhiqiu commented on dataset.py
> +    def correlation(self, our_scores, human_scores, verbose=True):
Why do we need the verbose?

2025-01-10 07:41 UTC, linzhiqiu requested changes

2025-01-10 07:41 UTC, linzhiqiu commented on genai_image_eval.py
> +    num_prompts = 1600 # number of prompts in GenAI-Bench（1600 in GenAI-Bench paper; 527 in VQAScore paper）
You shouldn't hard code this. You should make it an argparse param?

2025-01-10 08:08 UTC, linzhiqiu approved these changes

2025-01-10 08:08 UTC, merged